language: python

python:
    - 3.4
    - 3.5

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

install:
    - pip install -Ur requirements-dev.txt
    - pip install -e .
    - pip install coveralls

script:
    - make flake
